### ISSUE TITLE
Multi-targeting considerations

### ISSUE THREAD

**Issue by IEvangelist** [microsoft/kiota-abstractions-dotnet#185]
This library is targeting `netstandard2.0`, `netstandard2.1`, and `net5.0`. I believe it's in our best interest and the interest of the consuming libraries that this keeps up with .NET versions.

- `net5.0` is out of support, and support ended May 10, 2022 (going on nearly two years ago).

Here's the latest details of the supported versions, https://dotnet.microsoft.com/platform/support/policy.

It would be awesome to try to follow along with these major releases.

**Comment by baywet** [comment]
Hi @IEvangelist,
Thanks for starting the conversation here.

here is the reasoning behind the different targets:
- netstandard2.0: this is the last version supported by netfx and we wanted to keep netfx support.
- net5: this was [the recommended target at the time of initial publishing](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#when-to-target-net80-vs-netstandard), and removing it would be a binary breaking change. It is still recommended to target net5 as a lib for now as it provides broader compatibility to runtimes not maintained by Microsoft.
- netstandard2.1: I remember going back and forth with this one during testing. It's mostly here because of some edge cases in compatibility matrices for some projects as far as I can remember.

When moving to v2, we might consider dropping netfx support, and probably moving to a single target of net6 or net8 depending on the timelines. But nothing is decided on this front yet.

Also @andrueastman might have more context to provide here.

**Comment by andrueastman** [comment]
To add more context here. 

- net5: Was the recommended target at time of initial publishing. Target was mainly added to support trimming for AOT(otherwise a netstandard target would suffice given the target support). Since its a binary breaking change dropping this, this would ideally move up to the next LTS version depending on timeline for v2.
- netstandard2.1: Language features for C# versions below 8 don't work too well(Such as NRT). 

I believe a netstandard target [will work](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#when-to-target-net80-vs-netstandard) well for NET8 runtime. From a library perspective, the real question really is whether we'll drop netfx support. If we do, multitargeting concerns are simplified and we should reduce the target matrix to possibly one target.

**Comment by hwoodiwiss** [comment]
From a devex PoV for the library, it might be good to add .NET 8.0 support so that `<IsAotCompatible>` can be applied to the project. This will make it easy to catch trimming analyzer warnings at compile time.

**Comment by baywet** [comment]
Isn't it already supposed to emit trim warning with net5 target?

**Comment by hwoodiwiss** [comment]
From working with the projects locally, `IsTrimmable`seems to miss some of the trimming issues that `IsAotCompatible` finds, like incorrect or incomplete propagation of `DynamicallyAccessedMembersAttribute`.

**Comment by hwoodiwiss** [comment]
My comments above are incorrect and so off-topic. I think this check in the csproj is broken at the moment: https://github.com/microsoft/kiota-abstractions-dotnet/blob/main/src/Microsoft.Kiota.Abstractions.csproj#L37.

If I change `"'$(TargetFrameworkVersion)'` == 'net5.0'" to `"'$(TargetFramework)' == 'net5.0'"`, I get the same expected trimmer warning. I think this is worth opening a separate issue for, would it be okay to open one issue here to track this across the other .NET Kiota repositories?

**Comment by hwoodiwiss** [comment]
Maybe worth re-opening, I've been trying to make use of the trimming support, but it doesn't seem to work correctly.
This is supported by the fact that with the .NET 9 compiler, I get a warning stating that IsTrimmable isn't supported below .NET 6.

I think it would make sense to add explicit support for the 2 LTS releases that have come out since .NET 5.

**Comment by baywet** [comment]
For everyone's context the discussion is continuing at #196
