### ISSUE TITLE
Add net8.0 as a supported TFM

### ISSUE THREAD

**Issue by hwoodiwiss** [microsoft/kiota-abstractions-dotnet#196]
At the moment, the Kiota libraries are trim-annotated for the the .NET 5 tfm, _however_ I have a use-case where an application that transiently references the Kiota libraries via https://github.com/octokit/dotnet-sdk (currently testing against a local copy updated to the latest Kiota libraries) seems to instead prefer to select the netstandard2.0 package, my guess is this is because net5.0 is out of support. This causes trimmer warnings, which as of SDK version 9, are now included by `TreatWarningsAsError`.

I suspect this is also a cause for the significantly larger than expected binary size when this library is included (an additional 80MB) though that could be more down to the Octokit library.

It would be useful for this case for the Kiota libraries to be published targetting the net8.0 tfm as well, and have all of the AOT analyzers enabled in that case via `<IsAotCompatible>`.

Also of note, as of .NET SDK 9.0.100-preview.1.24101.2, I now get the warning:

```
C:\Program Files\dotnet\sdk\9.0.100-preview.1.24101.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): warning NETSDK1212: IsTrimmable and EnableTrimAnalyzer are not supported for the target framework. Consider multi-targeting to a supported framework to enable trimming, and set IsTrimmable only for the supported frameworks. For example: [R:\source\repos\kiota-abstractions-dotnet\src\Microsoft.Kiota.Abstractions.csproj]
C:\Program Files\dotnet\sdk\9.0.100-preview.1.24101.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): warning NETSDK1212: <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable> [R:\source\repos\kiota-abstractions-dotnet\src\Microsoft.Kiota.Abstractions.csproj]
```

On the net5.0 builds, which indicates to me that the trim analysis on the net5.0 build is non-functional at the moment as well.

**Comment by andrueastman** [comment]
Thanks for raising this @hwoodiwiss,

> seems to instead prefer to select the netstandard2.0 package,

Just to confirm(again), this still happens even after the change you made in https://github.com/microsoft/kiota-abstractions-dotnet/pull/187/files to fix the condition?

**Comment by hwoodiwiss** [comment]
Yeah, this is with a local build of https://github.com/octokit/dotnet-sdk with all of the Kiota libraries at their latest versions, including a local build of [kiota-serialization-text-dotnet](https://github.com/microsoft/kiota-serialization-text-dotnet) as the condition fix hasn't been published yet.

**Comment by baywet** [comment]
Thanks for reporting this.
It's strange that netstandard2.0 ends up being resolved, it should at very least be netstandard2.1 if not net5. (or could it be because all runtimes that supported 2.1 and didn't support net6 are now all out of support as well?)
It'd be nice if the dotnet team could put together more detailed guidelines for the library authors because the [blanket statement of targeting net 8, which used to be net 6, and before that net5](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#suggested-targets), it feels like aiming at a "moving target" (pun intended).

Since we already target net5 in an effort for broad compatibility, and since [net 6 goes out of support in November this year](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle), net 7 this may, and net 8 November 2026, here is my suggestion:
- Add net 6 (broader compatibility base)
- Add net 8 (future proof)
- Not adding net 7 (out of support soon, and the upgrade from net7 to 8 is pretty seamless) 

Thoughts?

**Comment by baywet** [comment]
ok great, do you want to get us started with the pull requests?

**Comment by hwoodiwiss** [comment]
> ok great, do you want to get us started with the pull requests?

Yeah, happy to, I'll have a look tonight (GMT)

**Comment by andrueastman** [comment]
Thanks for the contributions @hwoodiwiss

I believe the relevant packages are released available now for use..
