### ISSUE TITLE
RequestInformation.AddQueryParameters should add parameters based on the template as well as object

### ISSUE THREAD

**Issue by seruminar** [microsoft/kiota-abstractions-dotnet#81]
## Using
- Kiota 1.1.3
- Microsoft.Kiota.Abstractions 1.1.1

Given:
```
//Generated ApiRequestBuilder

UrlTemplate = "{+baseurl}/api{?Parameter*}"
```
and
```
// Generated ApiRequestBuilder query parameters class

public class RequestBuilderGetQueryParameters {
    public string? Parameter { get; set; }
}
```
(Note no `QueryParameterAttribute` was generated)

and user code like
```
var response = await apiClient.Api.GetAsync(request =>
    request.QueryParameters = new()
    {
        Parameter = someParameter
    });

```

Then something like this happens:
1. The generated code has a call to `requestInfo.AddQueryParameters(requestConfig.QueryParameters)`
2. `AddQueryParameters` uses `x.Name.ToFirstCharacterLowerCase()`, which makes the `Parameter` property add itself as `parameter`
3. The later getter of `URI`, which uses `parsedUrlTemplate.SetParameter(queryStringParameter.Key, GetSanitizedValue(queryStringParameter.Value))` will not set the value due to the casing mismatch
4. The full request is missing a query parameter set at a high level using the unmodified generated code

My solution was to adjust the template, but ideally I want to keep generated code unmodified. Given all that, can we please clarify:

- Is this expected, or is a `QueryParameterAttribute` missing from the generated code?
- Is there a requirement in the OpenAPI document to have a specific casing to lead to the URL template to use camelCase?
- Is there a reason to have case-sensitivity between the URL template, the query class, and the mechanism that converts the query class to the request URL?

**Comment by ichbinsteffen** [comment]
@baywet Personally I'm quite happy that my change is merged, thank you for the quick review! 
However I've gone back to investigate some more, because
I asked myself, why does the UrlTemplate from the Taven library default to case sensitive url templates and I think the answer is in the spec they mention in their repository: [URI Template Spec RFC6570](http://tools.ietf.org/html/rfc6570). 
In section 2.3 it states:

> _Variable names are case-sensitive because the name might be expanded
   within a case-sensitive URI component._
   
   So after all I think removing the `.ToFirstCharacterLowerCase()` might have been the better solution.
   Do you know why that lower-casing was implemented in the first place?

**Comment by baywet** [comment]
Thank you everyone for your patience on the matter.
This now has been fixed with https://github.com/microsoft/kiota-abstractions-dotnet/pull/129 and 1.3.3
The generation now conserves casing as an attribute, and any casing normalization has been removed from the code.
Closing. Don't hesitate to comment if something else is missing.
